Feature and Admin Upgrade/Overhaul
azerothcore/mod-solocraft pull request #13
Opened 2021-01-26 18:33 UTC by LannyE

This is a large overhaul of the Solocraft module.

Features and Admin Controls added:

-Groups now work. Difficulty is now distributed across group size
-Debuff added for groups trying to exceed the difficulty modifier
-Debuff can be enabled and disabled
-Spellpower is now scaled based on character level and modifier
-Stat modifier can now be changed in config to reel in melee damage
-Individual modification of each dungeon/raid difficulty
-Max level cap to keep high level characters from getting buffed
-Max level cap modifiable in config for each dungeon/raid
-Dungeon/Raid types still used as a catch all if not found as an
individual instance in the config

A database table is included to manage groups and the difficulty
modifier that each group member has applied to them. It also
deals with server restarts and players having to log out and log
back in to try to correct stats. The table is required.

Updated README.md file with current instructions and config file name fix.

Fixes #9

Testing:

Debuff:
-Character in dungeon with full difficulty modifier applied while not in a group.
-Invite another character to the group.
-Have new group member enter same dungeon.
-Debuff will be applied because of the group member already in the dungeon
has the full difficulty modifier applied.
-Have both/all characters leave dungeon and re-enter it to have the modifier
balanced across the current members of the group.

-Max Level:
-Solocraft.Max.Level.Diff and the Dungeon individual level are added together
to declare the max level a character can be to get the difficulty modifier
applied for the dungeon.
-Use a character whose level is higher than the max level and enter dungeon.
-Character should not receive the difficulty modifier buff for the dungeon.

-Spellpower and Stats modifier adjustments:
-Change modifier in the config.
-Enter dungeon with character and notice stats and/or spellpower numbers
changed from previous entrance into the dungeon.

2021-01-26 19:52 UTC, Helias commented
Now this has conflicts with the other PR that I just merged :sweat_smile: 
Solve conflicts please

2021-01-26 20:05 UTC, LannyE commented
This is an adventure.   You can definitely tell I am new to this.  Hopefully they have been resolved correctly.

2021-01-26 23:11 UTC, Helias commented
great job!

2021-01-26 23:19 UTC, Helias requested changes

2021-01-26 23:19 UTC, Helias commented on src/Solocraft.cpp
>                  difficulty = D10;
conver this into a switch-case or better, into an hashmap pls

2021-01-26 23:19 UTC, Helias commented on src/Solocraft.cpp
>      }
even here, a hashmap is a lot better, you can even improve the configs variables

2021-01-26 23:19 UTC, Helias commented on src/Solocraft.cpp
> +	}
if you create a hashmap you don't need all of this code

2021-01-26 23:25 UTC, Helias requested changes

2021-01-26 23:25 UTC, Helias commented on src/Solocraft.cpp
> +	}
exapmle:
```C++
#include <unordered_map>
std::unordered_map<uint32, uint32> dungeons = {
  { 33, sConfigMgr->GetIntDefault("Solocraft.ShadowfangKeep.Level", 15) }
};
```

and to use it as dunLevel you can just use
```C++
dunLevel = deungeons[map->GetId()];
```
or better, `return  deungeons[map->GetId()];`

2021-01-28 17:38 UTC, LannyE commented
Thanks for showing me the hashmap option.  That greatly reduced the number of lines of code.   I made the changes and did some testing.  It seems to be working fine.

2021-01-28 18:00 UTC, Helias approved these changes

2021-01-28 18:01 UTC, Helias commented
It is much better, doesn't it? :grin: 
Good job!

2021-01-28 18:12 UTC, Helias commented
I improved the comments next-to the dungeons.
Anyways, a hints for the future, convert `tabs` into `spaces` :wink: 

I will wait the build and merge it if the bild succeed.

2021-01-28 18:33 UTC, LannyE commented
The changes looks good.  Thank you for all your help. I appreciate your patience while I navigate this learning curve.  I haven't programmed in C++ for about 20+ years and never used Git (which is obvious).  On a side note: I also have a bunch of database changes for the lunar event and a new module I made based off a script I found.  Once I get some free time I will take a shot at uploading those.

2021-01-28 18:42 UTC, LannyE commented
Also this push should fix issue #3.  I used the testing done in that issue to form the logic and config settings.

2021-01-28 18:44 UTC, Helias commented
About #3 I edited the description of the PR so when we merge the PR the issue will be closed, for the module and lunar make a PR and create a repo with your module ;-)

2021-01-28 18:54 UTC, merged